/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Project name: Sample Project
 * Environment: Production
 * Project Id: 3016cfc2-49d6-00f5-72aa-7ef6c7af98f7
 */
export const assetFolders = {
  /**
   * Café locations
   */
  caféLocations: {
    id: '958001d8-2228-4373-b966-5262b5b96f71',
    name: 'Café locations',
    externalId: undefined,
    folders: {},
  },
};
