/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Project name: Sample Project
 * Environment: Production
 * Project Id: 3016cfc2-49d6-00f5-72aa-7ef6c7af98f7
 */
export const languages = {
  /**
   * English (United States)
   */
  enUS: {
    codename: 'en-US',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'English (United States)',
  },

  /**
   * Spanish (Spain)
   */
  esES: {
    codename: 'es-ES',
    id: 'd1f95fde-af02-b3b5-bd9e-f232311ccab8',
    isActive: true,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Spanish (Spain)',
  },
};
