const hostedVideoResolver = require('../resolvers/hosted-video-resolver');
const { ContentItem } = require('kentico-cloud-delivery');

/**
* This class was generated by 'kentico-cloud-model-generator-utility' at Wed Dec 05 2018 10:36:54 GMT-0500 (Eastern Standard Time).
*/
class HostedVideo extends ContentItem {
        constructor() {
        super({
            richTextResolver: ((item) => hostedVideoResolver.resolveModularContent(item)),
            propertyResolver: ((fieldName) => {
                if (fieldName === 'video_id') {
                    return 'videoId';
                }
                if (fieldName === 'video_host') {
                    return 'videoHost';
                }
                return fieldName;
            })
        });
    }
}
module.exports = HostedVideo