const tweetResolver = require('../resolvers/tweet-resolver');
const { ContentItem } = require('kentico-cloud-delivery');

/**
* This class was generated by 'kentico-cloud-model-generator-utility' at Wed Dec 05 2018 10:36:54 GMT-0500 (Eastern Standard Time).
*/
class Tweet extends ContentItem {
        constructor() {
        super({
            richTextResolver: ((item) => tweetResolver.resolveModularContent(item)),
            propertyResolver: ((fieldName) => {
                if (fieldName === 'tweet_link') {
                    return 'tweetLink';
                }
                if (fieldName === 'display_options') {
                    return 'displayOptions';
                }
                return fieldName;
            })
        });
    }
}
module.exports = Tweet